language: node_js

node_js:
  - "8"

sudo: required

services:
  - docker

after_deploy:
  - echo "done deploying"

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID2
  secret_access_key:
    secure: "$SECRETACCESSKEY2"
  region: "us-east-2"  
  app: "dockerapp"
  env: "Dockerapp-env"
  bucket_name: "elasticbeanstalk-us-east-2-495172234766"
  on:
    branch: master